export const actionTypes = {
  CREATE_PARCEL: "CREATE_PARCEL",
  UPDATE_PARCEL: " UPDATE_PARCEL",
  DELETE_PARCEL: "DELETE_PARCEL",
  ALL_PARCELS: "ALL_PARCELS",
  ONE_PARCEL: "ONE_PARCEL",

  AUTH: "AUTH",
  LOGOUT: "LOGOUT",
};
